apiVersion: v1
kind: Service
metadata:
  name: {{ include "jacoku.fullname" . }}
  labels:
    {{- include "jacoku.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 1219
      protocol: TCP
      name: http
  selector:
    jacoku: {{ include "jacoku.fullname" . }}
    {{- include "jacoku.selectorLabels" . | nindent 4 }}
