{{- if .Values.frontService.create -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jacoco-report.fullname" . }}-front
  labels:
    {{- include "jacoco-report.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "jacoco-report.selectorLabels" . | nindent 4 }}
    jacoco-report: {{ include "jacoco-report.fullname" . }}-front
{{- end}}
