site_name: jacoco-report代码覆盖率报告
site_url: https://guohai163.github.com/jacoco-report
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - content.code.copy



  include_sidebar: true

nav:
  - 快速开始:
    - 项目介绍: "index.md"
    - 快速部署: "depl.md"
  - 完整环境说明:
    - 流程介绍: "full-depl/flow-chart.md"
    - 测试对象准备: "full-depl/test-object.md"
    - 进行测试: "full-depl/testing.md"
    - 生成中间文件: "full-depl/jacoco-report.md"